
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HWImplService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/hello?wsdl")
public class HWImplService
    extends Service
{

    private final static URL HWIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HWIMPLSERVICE_EXCEPTION;
    private final static QName HWIMPLSERVICE_QNAME = new QName("http://server/", "HWImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HWIMPLSERVICE_WSDL_LOCATION = url;
        HWIMPLSERVICE_EXCEPTION = e;
    }

    public HWImplService() {
        super(__getWsdlLocation(), HWIMPLSERVICE_QNAME);
    }

    public HWImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HWIMPLSERVICE_QNAME, features);
    }

    public HWImplService(URL wsdlLocation) {
        super(wsdlLocation, HWIMPLSERVICE_QNAME);
    }

    public HWImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HWIMPLSERVICE_QNAME, features);
    }

    public HWImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HWImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerFunc
     */
    @WebEndpoint(name = "HWImplPort")
    public ServerFunc getHWImplPort() {
        return super.getPort(new QName("http://server/", "HWImplPort"), ServerFunc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerFunc
     */
    @WebEndpoint(name = "HWImplPort")
    public ServerFunc getHWImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "HWImplPort"), ServerFunc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HWIMPLSERVICE_EXCEPTION!= null) {
            throw HWIMPLSERVICE_EXCEPTION;
        }
        return HWIMPLSERVICE_WSDL_LOCATION;
    }

}
