
package thehello;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://thehello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<thehello.HelloWorldResponse>
     */
    @WebMethod(operationName = "HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://thehello/", className = "thehello.HelloWorld_Type")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://thehello/", className = "thehello.HelloWorldResponse")
    public Response<HelloWorldResponse> helloWorldAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://thehello/", className = "thehello.HelloWorld_Type")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://thehello/", className = "thehello.HelloWorldResponse")
    public Future<?> helloWorldAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<HelloWorldResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://thehello/", className = "thehello.HelloWorld_Type")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://thehello/", className = "thehello.HelloWorldResponse")
    @Action(input = "http://thehello/HelloWorld/HelloWorldRequest", output = "http://thehello/HelloWorld/HelloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
