import helloworld_class_only.HelloWorld;
import helloworld_class_only.HelloWorldService;

public class HelloWorldClient {
	public static void main(String[] args) {

	// HelloWorldService_Service is a class
	HelloWorldService myHelloWorld = new HelloWorldService();

	// In this case, HellOWorld was generated by wsimport as an interface class
	HelloWorld myinterface = myHelloWorld.getHelloWorldPort();
	

        //Note the format of the operation call "helloWorld".  This
	//matches the format in the wsimport-generated HelloWorld.java file.
	String response = myinterface.helloWorld(args[0]);


    System.out.println("response is "+response);
   }
}
