import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


import thehello.HelloWorld;
import thehello.HelloWorldService;

public class HelloWorldClient_Async {
	public static void main(String[] args) {

	// HelloWorldService_Service is a class
	HelloWorldService myHelloWorld = new HelloWorldService();

	// In this case, HellOWorld was generated by wsimport as an interface class
	HelloWorld myinterface = myHelloWorld.getHelloWorldPort();
	

        Response<thehello.HelloWorldResponse> 
        response = myinterface.helloWorldAsync(args[0]);

       String theresponse="";
       try {

         while ( !response.isDone() ) {
           System.out.println("doing useful work");
         }


         // get the response itself
         thehello.HelloWorldResponse myresponse = response.get();

        // retrieve the string from within the response
         theresponse = myresponse.getReturn();
       }
       catch (InterruptedException e) {
        e.printStackTrace();
       } 
       catch (Exception e) {
        e.printStackTrace();
       } 
       System.out.println("Final response is "+theresponse );

   }
}
