
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerAPI", targetNamespace = "http://server/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServerAPI {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(partName = "return")
    @Action(input = "http://server/ServerAPI/HelloWorldRequest", output = "http://server/ServerAPI/HelloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "StudentEnter")
    @WebResult(partName = "return")
    @Action(input = "http://server/ServerAPI/StudentEnterRequest", output = "http://server/ServerAPI/StudentEnterResponse")
    public String studentEnter(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1);

}
