
package myhelloworld_soap12;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWorldService", targetNamespace = "http://myHelloWorld_SOAP12/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://myHelloWorld_SOAP12/", className = "myhelloworld_soap12.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://myHelloWorld_SOAP12/", className = "myhelloworld_soap12.HelloWorldResponse")
    public String helloWorld(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
